### ISSUE TITLE
sudo --preserve-env  mix  gatling.deploy returns no function clause matching IO.chardata_to_string/1

### ISSUE THREAD

**Issue by Preen** [hashrocket/gatling#59]
When I run `MIX_ENV=prod sudo --preserve-env  mix  gatling.deploy my_app` I get this error:

    ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1

    The following arguments were given to IO.chardata_to_string/1:

        # 1
        nil

    (elixir) lib/io.ex:445: IO.chardata_to_string/1
    (elixir) lib/path.ex:500: Path.do_join/3
    (elixir) lib/path.ex:495: Path.join/2
    (elixir) lib/path.ex:472: Path.join/1
    lib/gatling/gatling.ex:19: Gatling.env/2
    lib/gatling/tasks/deploy.ex:28: Mix.Tasks.Gatling.Deploy.deploy/1
    (mix) lib/mix/task.ex:301: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:75: Mix.CLI.run_task/2

I have a elixir cluster project with one phoenix app inside it. This is on Ubuntu 16.04 LTS. I can compile the project in production mode on local computer.

**Comment by tgautier** [comment]
Same issue here, I've found that gatling was looking for `:version` and `:app` in your `mix.exs` `project` function.

After having added those, I now run into the following cryptic error:

```
warning: redefining module MyApp.Mixfile (current version defined in memory)
  nofile:1

** (Mix) Trying to load MyApp.Mixfile from "nofile" but another project with the same name was already defined at "nofile"
```

It looks like this project is no longer active.

**Comment by ConnorRigby** [comment]
I have this issue also. Any resolution?
